---
platform: linux

image_resource:
  type: docker-image
  source: {repository: idahobean/dcind-golang-npm}

inputs:
- name: verdaccio
- name: git-resource
- name: npm-resource
  # path: gopath/src/github.com/Chad-Mowbray/npm-resource
- name: sample-node

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/Chad-Mowbray/npm-resource/scripts/ci
  # path: echo
  # args: [hello]
